### ISSUE TITLE
docker-compose pull failure (as of 1:00 pm Sunday 2-12-2018)?

### ISSUE THREAD

**Issue by RichardBruskiewich** [galaxy-genome-annotation/dockerized-gmod-deployment#10]
I'm strongly suspecting that this project is in transition towards full implementation.. cutting and pasting its way to fulfillment! That would perhaps explain the following error?

```
ubuntu@divseek-canada-docker-gmod:/opt/divseekcanada/dockerized-gmod-deployment$ docker-compose pull
Pulling galaxy              ... done
Pulling apollo_db           ... done
Pulling tripal_db           ... done
Pulling chado_jb            ... done
Pulling pgadmin4            ... done
Pulling postgraphql-refseqs ... done
Pulling postgraphql         ... done
Pulling postgrest           ... done
Pulling apollo              ... done
Pulling remoteuser          ... done
Pulling elasticsearch       ... **error**
Pulling tripal              ... done
Pulling jbrowse             ... **error**
Pulling jbrowse-graphql     ... **error**
Pulling proxy               ... done

**ERROR: for jbrowse  b'manifest for quay.io/galaxy-genome-annotation/jbrowse:1.12.5 not found'**

**ERROR: for jbrowse-graphql  b'manifest for quay.io/galaxy-genome-annotation/jbrowse:1.12.5 not found'**

**ERROR: for elasticsearch  b'manifest for elasticsearch:latest not found'**
**ERROR: manifest for quay.io/galaxy-genome-annotation/jbrowse:1.12.5 not found**
**manifest for quay.io/galaxy-genome-annotation/jbrowse:1.12.5 not found**
**manifest for elasticsearch:latest not found**
```
maybe the following will fix (in the docker-compose.yml file?):

```yml
  elasticsearch:
    # I don't see a 'latest' tag in the elasticsearch repo; maybe need to explicitly tag an available release?
    image: **docker.elastic.co/elasticsearch/elasticsearch:6.51**  # latest seems to be 6.5.1?
  jbrowse:
    image: quay.io/galaxy-genome-annotation/jbrowse:**v**1.12.5
    volumes_from:
        - "galaxy:ro"

  jbrowse-graphql:
    image: quay.io/galaxy-genome-annotation/jbrowse:**v**1.12.5
    volumes:
        - "./jbgraphql:/data"
```

**Not too sure about the jbrowse-graphql... doesn't seem to have its own image yet?**
